services:
  client:
    build:
      context: ./frontend
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  server:
    build:
      context: ./backend
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001