services:
  client:
    depends_on:
      - server
    build:
      context: ./frontend
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

  server:
    depends_on:
      - mysql
    build:
      context: ./backend
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001

volumes:
    mysql: